os: osx
language: cpp

compiler:
  - clang

install:
  - git submodule update --init --depth 1

script:
  - xcodebuild -project build/PomdogTest.xcodeproj clean
  - xcodebuild -project build/PomdogTest.xcodeproj
  - build/build/Release/PomdogUnitTest

notifications:
  email: false
