language: objective-c

compiler:
  - clang

install:
  - git clone https://github.com/mogemimi/pomdog-third-party.git third-party
  - git clone https://chromium.googlesource.com/external/gyp.git tools/gyp
  - git clone https://github.com/srz-zumix/iutest.git third-party/iutest

script:
  - tools/gyp/gyp build/unittest.gyp --depth=. -f xcode --generator-output=build.xcodefiles
  - xcodebuild -project build.xcodefiles/build/unittest.xcodeproj clean
  - xcodebuild -project build.xcodefiles/build/unittest.xcodeproj
  - build/build/Release/unittest

notifications:
  email: false
