language: objective-c

compiler:
  - clang

install:
  - git clone --depth=1 https://github.com/mogemimi/pomdog-third-party.git third-party
  - git clone --depth=1 https://chromium.googlesource.com/external/gyp.git tools/gyp
  - git clone --depth=1 https://github.com/srz-zumix/iutest.git third-party/iutest

script:
  - tools/gyp/gyp test/FrameworkTest/unittest.gyp --depth=. -f xcode --generator-output=build.xcodefiles
  - xcodebuild -project build.xcodefiles/test/FrameworkTest/unittest.xcodeproj clean
  - xcodebuild -project build.xcodefiles/test/FrameworkTest/unittest.xcodeproj
  - test/FrameworkTest/build/Release/unittest

notifications:
  email: false
